name = "comhttp"
type = "webpack"
account_id = 'f120f7bc8cdd17d30c0e5c2438c82558'
route = '*.com-http.*'
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./build",entry-point = "./workers-site"}
